vtex-apps/order-placed

react/OrderPlaced.js, react/components/Header/Header.js, react/components/Header/OrderSummary.js, react/components/Header/Warnings.js, react/components/OrderInfo/BasicInfo.js, react/components/OrderInfo/OrderInfo.js, react/components/OrderInfo/StorePickUpInfo.js
Add CSS classes from VTEX Tachyons to make each component responsive to
different screen sizes.
Broken layouts on different screen sizes.
- [  ] Bug fix (non-breaking change which fixes an issue)
- [  ] Breaking change (fix or feature that would cause existing functionality to change)
- [  ] Requires change to documentation, which has been updated accordingly.
=> Responsive components

react/OrderPlaced.js, react/components/Header/Header.js, react/components/OrderInfo/CustumerInfo.js, react/components/OrderInfo/OrderInfo.js, react/components/OrderInfo/Payment/PaymentMethod.js, react/components/OrderInfo/Payment/PaymentSummary.js, react/components/OrderInfo/ProductList.js, react/components/OrderInfo/Shipping/Shipping.js, react/components/OrderInfo/Shipping/ShippingHeader.js, react/components/OrderInfo/StorePickUp/StorePickUp.js, react/components/OrderInfo/StorePickUp/StorePickUpHeader.js, react/graphql/getOrder.graphql, react/graphql/getOrderGroup.graphql, react/package.json, react/proptypes/shapes.js, react/test-cases/1-delivery.js, react/test-cases/1-many-delivery.js, react/test-cases/1-pickup.js, react/test-cases/3-pickup-only-2-delivery-only.js, react/yarn.lock
Add support for an order that contains items that will be delivered and items that will be picked-up at a pick-up point.
Better coverage of possible checkout scenarios.
=> Handle different deliveryChannels

.gitignore, messages/en.json, messages/pt.json, react/components/Header/Warnings.js, react/components/Header/index.js, react/components/OrderInfo/OrderHeader.js, react/components/OrderInfo/OrderOptions.js, react/components/OrderInfo/OrderTotal.js, react/components/OrderInfo/index.js, react/components/ProductList/Product.js
Make adjustments to a components that would not behave as they should in mobile devices.
=> Adjustments to mobile UI

messages/en.json, messages/pt.json, react/components/OrderInfo/index.js, react/components/Payment/PaymentMethod.js, react/graphql/getOrderGroup.graphql, react/mocks/twoDeliveries.js
Add support for displaying IDs of transactions and individual payments.
=> Payment additional information

.vtex/cy.yml, .vtex/deploy.yml, .vtex/deployment.json, manifest.json, react/.eslintrc, react/OrderPlaced.js, react/components/OrderInfo/index.js
Integrate OrderPlaced to the Dreamstore checkout, making it possible to complete a purchase and be redirected to the new OrderPlaced page.
=> Checkout integration

react/components/OrderInfo/OrderSection.tsx, react/components/OrderInfo/OrderTotal.tsx, react/components/ProductList/Product.tsx, react/components/ProductList/index.tsx, react/components/Shipping/index.tsx, react/components/StorePickUp/StorePickUpHeader.tsx, react/components/StorePickUp/index.tsx
Update layout to better utilize screen space.
=> New layout for `Shipping`, `StorePickUp` and `OrderSummary` components

react/Icons/Info.tsx, react/Icons/Tooltip.tsx, react/Icons/utils.tsx, react/components/Header/index.tsx, react/components/OrderInfo/index.tsx, react/components/Payment/AddittionalInfo.tsx, react/components/Payment/PaymentMethod.tsx, react/components/StorePickUp/StorePickUpHeader.tsx
Update the way additional information on payments is shown to the user.
https://victorhugov1--vtexgame1.myvtex.com/checkout/orderPlaced/?og=906892698339
=> New payment additional info tooltip

CHANGELOG.md, manifest.json, package.json, react/Skeleton.tsx, react/components/Address.tsx, react/components/Header/Summary.tsx, react/components/Header/Warnings.tsx, react/components/Header/index.tsx, react/components/OrderInfo/OrderHeader.tsx, react/components/OrderInfo/OrderOptions.tsx, react/components/OrderInfo/OrderTotal.tsx, react/components/OrderInfo/index.tsx, react/components/Payment/PaymentMethod.tsx, react/components/ProductList/Product.tsx, react/components/ProductList/index.tsx, react/components/Shipping/index.tsx, react/components/StorePickUp/StorePickUpHeader.tsx, react/components/StorePickUp/index.tsx
Additional layout fixes made along with @alinevillaca :)
`cd react && yarn test`
=> Layout fixes

CHANGELOG.md, README.md, manifest.json, messages/context.json, messages/en.json, messages/pt.json, package.json, react/Analytics.tsx, react/OrderPlaced.tsx, react/__mocks__/vtex.pixel-manager/PixelContext.tsx, react/graphql/getOrderGroup.graphql, react/typings/global.d.ts, react/typings/render.d.ts, react/typings/vtex.pixel-manager.d.ts
Add support for analytics using `Pixel` for Google Tag Manager.
There was no analytics at all being sent by OrderPlaced.
=> Analytics support

CHANGELOG.md, manifest.json, package.json, react/Analytics.tsx
=> Migrate to pixel manager v1

CHANGELOG.md, messages/en.json
Fix wrong translation caused by #64
Wrong translation of 'unit' and 'units'.
=> Fix unit translation for english

CHANGELOG.md, messages/en.json
https://app.clubhouse.io/vtex/story/19181/ajuste-de-traducao-orderplaced
Wrong generic english translation
Tis' only a translation
---
=> Change translation of "you'll" to "you will"

CODEOWNERS
As mentioned on the title, this project should be reviewed by at least one person from the @vtex-apps/post-purchase-front
#trivial
=> Add codeowners file to assign post-purchase front team as reviewers

react/Analytics.tsx, react/index.tsx
Uncomment analytics component and remove order group mock.
=> Uncomment analytics component #trivial

CHANGELOG.md, messages/en.json, react/__tests__/Header.test.tsx
=> (1.x) Fix English translation of 'business'

CHANGELOG.md, messages/en.json, react/__tests__/Notices.test.tsx
=> Fix English translation of 'business'

CHANGELOG.md, manifest.json, react/package.json
This reverts commit fd8451788911fe3b5369038180e33054732e9581.
Revert last accidental release commit 😢 
ditto.
n/a
=> Revert "Release v3.0.0"

docs/README.md, react/Footer.tsx, react/index.tsx, store/interfaces.json
Add a `footer` block to be able to add content to the bottom of the order-placed page.
Forgot this one 🤓 
wip
n/a
=> Add footer block

.github/workflows/pull-request.yml
This an [automated pull request](https://github.com/vtex/github-pull-request-script) that aims to:
- Add github pr action
- Add danger job
- Add test action job
- Add lint action job
When approved, feel free to merge it as if it was created by a bot account :robot:.
**#trivial**
=> Add workflow actions for linting and testing

docs/README.md, react/BankInvoiceSection.tsx, react/tsconfig.json
=> Adição CSS Handles

CHANGELOG.md, docs/README.md, react/components/PickUpHeader.tsx
I've added css handle to pickup point receiver name paragraph in order to add  style to it.
The message is a paragraph and it comes with default styling ex: margins.
Link the app.
=> added package receiver name css handle
