vtex-apps/order-placed

react/OrderPlaced.js, react/components/OrderInfo/OrderInfo.js, react/components/OrderInfo/OrderTotal.js, react/components/OrderInfo/Payment/PaymentMethod.js, react/components/OrderInfo/Product.js, react/components/OrderInfo/ProductList.js, react/components/OrderInfo/Shipping/Shipping.js, react/components/OrderInfo/StorePickUp/StorePickUp.js, react/components/OrderInfo/StorePickUp/StorePickUpHeader.js
Remove the need to pass down `currency` props from `OrderInfo` to child components.
Cleaner code and easier prop management.
=> Create new `React.Context` for store currency data

.vtex/cy.yml, react/.eslintrc, react/OrderPlaced.js, react/components/OrderInfo/index.js, react/components/ProductList/Product.js
`Product` component can handle products with measurement units different from 'un' and multipliers different from 1 better.
If the product had 'un' as measurement unit, but a multiplier different from 1, that would be ignored and not rendered.
=> Better measurement unit support

react/components/Header/BankInvoice/BarCode.js, react/components/Header/BankInvoice/Embedded.js, react/components/Header/BankInvoice/index.js, react/components/Header/Summary.js, react/components/Header/Warnings.js, react/components/Header/index.js, react/components/OrderInfo/OrderHeader.js, react/components/OrderInfo/OrderOptions.js, react/components/OrderInfo/OrderSplitNotice.js, react/components/OrderInfo/OrderTotal.js, react/components/Payment/PaymentMethod.js, react/components/ProductList/Product.js, react/components/Shipping/ShippingHeader.js, react/components/StorePickUp/StorePickUpHeader.js, react/utils/index.js
Add selected Sla to `ShippingHeader` so that it is displayed below the shipping estimate.
Also remove `intlMessage` function defined in `utils`in favor of using `intl.formatMessage()`.
=> Selected SLA

react/OrderPlaced.js, react/Skeleton.js, react/__mocks__/styleMock.js, react/package.json, react/styles.global.css
Add a loading skeleton to be displayed while the app is loading.
The app was using a simple spinner to indicate loading.
=> Create loading skeleton

react/components/ButtonLink.tsx, react/components/Header/BankInvoice/index.tsx, react/components/Header/Warnings.tsx, react/components/Header/index.tsx, react/components/OrderInfo/OrderHeader.tsx, react/components/OrderInfo/OrderOptions.tsx, react/components/Payment/PaymentMethod.tsx
Make buttons shown on `Header` and `OrderHeader` redirect the user to correct `MyAccount` route.
Also make `Print this page` button trigger `window.print()` to the browser.
Buttons had no links associated with them.
=> Integrate action buttons to Dreamstore routes

CHANGELOG.md, manifest.json, package.json, react/.eslintrc.json, react/.prettierrc, react/__mocks__/vtex.address-form.tsx, react/__mocks__/vtex.profile-form.tsx, react/__mocks__/vtex.render-runtime.tsx, react/__tests__/ProductList.test.tsx, react/components/OrderInfo/OrderHeader.tsx, react/components/Payment/PaymentMethod.tsx, react/components/ProductList/Attachment.tsx, react/components/ProductList/Product.tsx, react/components/ProductList/Subscription.tsx, react/package.json, react/tslint.json, react/typings/render.d.ts, react/utils/index.tsx, react/yarn.lock
Replace `tslint` with `eslint`.
TSLint is going to be deprecated, so we are slowly moving to ESLint with [typescript-eslint](http://typescript-eslint.io).
=> Migrate from tslint to eslint

CHANGELOG.md, messages/en.json
Fix `unit`, `units` translation.
Current translation is `unity` and `unities`.
Open an order-placed page and check the quantity number of a certain product.
=> Fix unit/units translation in english

CHANGELOG.md, react/__mocks__/vtex.order-details.tsx, react/__tests__/BankInvoice.test.tsx, react/components/Header/Warnings.tsx, react/components/Header/index.tsx, react/components/Payment/PaymentMethod.tsx, react/utils/index.tsx
- ditto.
- The checkout doesn't return the correct url when the user isn't indentified. Therefore we need to make him log in first before he can see the bank invoice it self.
https://felipe--boticario.myvtex.com/checkout/orderPlaced/?og=v83637215bot
=> Make the user log in before seeing the bank invoice.

CHANGELOG.md, manifest.json, react/OrderPlaced.tsx, react/components/OrderInfo/index.tsx, store/blocks.json, store/interfaces.json
Add `PromotionBanner` to `orderPlaced` to promote the installation of the web app and show prompt.
In the store settings, you can choose to show the [install prompt](https://developers.google.com/web/fundamentals/app-install-banners/promoting-install-mobile) when the first purchase is maded. 
[Workspace](https://thay--storecomponents.myvtex.com/checkout/orderPlaced/?og=949500478939)
=> Add promotion banner to promote web app in

CHANGELOG.md, docs/README.md
Change docs to make sure users don't forget to define de store.orderplaced in their theme.
=> Add page block to the docs

CHANGELOG.md, docs/README.md, react/OrderContext.tsx, react/OrderGroupContext.tsx
We need the context of the command that is being used by the vtex.order-placed@2.X component to be exported in order to access it from our own component exito.order-placed@3.X,
which shows how son vtex.order-placed@2.X with business customizations such as: plastic bag tax, accumulated colombian points and validation of payment with a exito card using an otp code.
For these customizations we need to use the information coming from the context of the vtex.order-placed@2.X command.
Resolve to be able to obtain the necessary information to carry out these customizations.
=> Export the order and order group contexts as hooks

CHANGELOG.md, react/OrderTotal.tsx, react/index.tsx
IE 11 doesn't support the `main` tag and React is complaining about it. This PR also fixes a possible duped `key`.
- Open https://mototest--motorolasandbox.myvtex.com/checkout/orderPlaced/?og=1031982999821 in a IE 11
=> Replace main tag with role=main

CHANGELOG.md, docs/README.md
Hello, the purpose of this PR is to solve the display of images on the VTEX Developers portal.
I transferred the images to the GitHub CDN. Following the good practices of this [link](https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d) in Gist.
Display the images on the vtex developers portal.
Just viewing on the website.
Below is the before and after with the solution of the problem:
=> Corrects images that do not display on the website

CHANGELOG.md, react/graphql/getOrderGroup.graphql
Add new field so it's possible to identify items that have assembly options.
https://orderplacedparent--storecomponents.myvtex.com/checkout/orderPlaced/?og=1082982841447
https://github.com/vtex/order-placed-graphql/pull/24
=> Add parentItemIndex in GraphQL query

CHANGELOG.md, react/OrderTotal.tsx
Removing assemblies from the items count.
Reference: https://github.com/vtex-apps/minicart/pull/260
The wrong count number on the screen
[Workspace](https://mcdon125--acctglobal.myvtex.com/checkout/orderPlaced/?og=1082931550390)
=> Removing assemblies from the items count

CHANGELOG.md, react/graphql/getOrderGroup.graphql, react/package.json, react/typings/global.d.ts, react/yarn.lock
App Store has a component (`AppPrice`) to show the app price. This component is rendered on the Product and Checkout pages. `AppPrice` does a query to `app-store-api` to get the price but this query has a `productId` as a variable.
```
const { data, loading } = useQuery<AppPriceQuery, QueryAppPriceArgs>(
APP_PRICE,
{
variables: { productId },
}
)
```
I would like to add the `productId` to the `getOrderGroup` query so then I will be able to consume this value from the `OrderGroupContext`.
`productId` property to `getOrderGroup` query
You must buy an app to `pilateslovers` account.  Click on `Get app` button and fill the input with `pilateslovers` value. 
You will log in and then you will be redirected to the product page again. Go to checkout clicking on `Get App` button again. Finish the …
=> Add productId property to getOrderGroup query

CHANGELOG.md, react/OrderTotal.tsx
Make it possible to make a CSS selector that targets just one totalizer.
Fixes #143 
https://breno2--storecomponents.myvtex.com/checkout/orderPlaced/?og=1119571095058
=> Add modifier to totalListItem CSS Handle

react/components/ProductList/Product.tsx, react/graphql/getOrderGroup.graphql, react/typings/global.d.ts
‘price’ attribute is used in product list instead of ‘sellingPrice’. So user is not able to see the discounted price(eg: in case of subscription orders) in order confirmation page for a product. Regular price is always displayed in order confirmation page even when their is a discount for a product.
Displays correct price for a product always.
It can be tested by placing any upsell /subscription order(with discounts).
Bug fix (non-breaking change which fixes an issue)
=> Fix to show product price after discount for each item in the list

CHANGELOG.md, react/components/BankInvoice/BarCode.tsx, react/utils/index.ts
ATTS
Currently, if an user places an order though smart checkout with bank invoice payment, the barcode is shown without requesting authentication. When the barcode is inserted into the bank app, it shows sensitive data from the buyer (like CPF), so we need to encrypt the barcode and request authentication to open it.
This PR adds the login request flow to open the barcode, and the encryption is done by [this other PR](https://github.com/vtex/sales-order-system/pull/368).
=> Fix barcode vulnerability

.vtex/catalog-info.yaml
This PR updates the owner of order-placed to te-0001 in the catalog-info.yaml file.
This is necessary because now in DK Portal we will define the team -> component relationship through the team id instead of the owner name.
=> Update owner of order-placed to te-0001
